Query by facets as links
alphagov/search-api pull request #1453
Opened 2019-03-07 14:23 UTC by peteglondon

# What
Allow rummager to index and query the following link types:

* facet_values
* facet_groups

As part of the work to address tech debt introduced by the [EU Exit business finder](https://www.gov.uk/find-eu-exit-guidance-business) and to [Improve the Business Finder tagging system](https://trello.com/c/zn5LBg3L/77-improve-the-business-finder-tagging-system).

We are introducing Facet Groups, Facets and FacetValues as content items.

Tagging to these things will then be done in `content-tagger` (similar to taxonomy) and implemented as links.

Trello: https://trello.com/c/RHl653OZ/245-rummager-query-on-facet-group-and-facet-value

2019-03-07 15:38 UTC, peteglondon commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mapping Rummager request/response in Finder Frontend](https://trello.com/c/Sd7omEFH/263-mapping-rummager-request-response-in-finder-frontend)

2019-03-08 09:45 UTC, peteglondon commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rummager query on facet group and facet value](https://trello.com/c/RHl653OZ/245-rummager-query-on-facet-group-and-facet-value)

2019-03-11 09:37 UTC, steventux requested changes
Looks good, one question around facet groups.

2019-03-11 09:37 UTC, steventux commented on lib/govuk_index/presenters/expanded_links_presenter.rb
> +      content_ids("facet_groups")
At the moment, the link from facet to facet group is in the `parent` links array https://github.com/alphagov/govuk-content-schemas/blob/master/formats/facet.jsonnet#L90 
I'm not sure where we get `facet_groups` from in expanded links

2019-03-12 10:28 UTC, steventux commented on lib/govuk_index/presenters/expanded_links_presenter.rb
> +      content_ids("facet_groups")
Having discussed this we've agreed that content either needs `facet_groups` links or the facet group to be present in the `facet_values` links, the former is more explicit see: https://github.com/alphagov/govuk-content-schemas/commit/90be6c695ae3f5827790c68d10cee7b61f16c7ae

2019-03-12 10:28 UTC, steventux approved these changes
LGTM

2019-03-12 11:49 UTC, merged