Add find brexit guidance finder definition
alphagov/search-api pull request #1654
Opened 2019-08-13 16:26 UTC by theseanything

This adds a definition file for a finder to support dynamic lists for Brexit guidance.

2019-08-14 14:46 UTC, DilwoarH requested changes

2019-08-14 15:30 UTC, barrucadu approved these changes
Looks OK to me, but maybe deploy it to integration before merging and make sure it's got everything you want

2019-08-15 09:26 UTC, tijmenb approved these changes

2019-08-15 09:50 UTC, DilwoarH approved these changes

2019-08-15 09:51 UTC, merged