Rake task to pull the learn to rank model from S3
alphagov/search-api pull request #1816
Opened 2019-11-29 16:41 UTC by laurentqro

2019-12-02 10:14 UTC, bilbof submitted a review, later dismissed

2019-12-04 11:28 UTC, sihugh requested changes
Code looks good 👍 

Would you be able to squash the commits up a bit?  Also, it'd be great if you could include the text from the PR in a commit somewhere, as it was useful context.

2019-12-04 15:29 UTC, laurentqro commented
Thank you for the review @sihugh, I've squashed all the commits into one and added the PR description to the commit message. 👌

2019-12-05 12:48 UTC, sihugh approved these changes

2019-12-06 10:07 UTC, merged