Update name for Democratic Republic of the Congo
alphagov/search-api pull request #700
Opened 2016-09-28 13:16 UTC by Davidslv

**trello**: https://trello.com/c/rxjklHjL/191-country-name-change-democratic-republic-of-the-congo

>The country formerly known as 'Democratic Republic of Congo' is now officially called 'Democratic Republic of **the** Congo'

2016-09-28 13:49 UTC, tijmenb requested changes

2016-09-28 13:49 UTC, tijmenb commented on config/schema/document_types/international_development_fund.json
> -        "value": "democratic-republic-of-congo"
Let's keep this value the same for now, so that we don't have to republish everything (if it's changed now, the search won't work).

2016-09-28 14:08 UTC, Davidslv commented on config/schema/document_types/international_development_fund.json
> -        "value": "democratic-republic-of-congo"
👍

2016-09-28 14:12 UTC, tijmenb approved these changes

2016-09-29 08:42 UTC, rubenarakelyan commented
👍

2016-09-29 08:42 UTC, merged