Index parents of the taxon for each page
alphagov/search-api pull request #748
Opened 2017-02-13 16:25 UTC by klssmith

Content tools would like to be able to fetch all content related to education.
We added a filter, part_of_taxonomy, that returns everything that is tagged
to the given taxon and any of that taxon's children.

Trello card: https://trello.com/c/dIMlC5JH/481-index-parents-of-the-taxon-for-each-page

Paired with @MatMoore

2017-02-13 16:39 UTC, tijmenb commented on config/schema/field_definitions.json
> +    "description": "Any taxon tagged to the document and any of their ancestor taxons",
Does "ancestor" imply that it's the _parents_ that are included?

2017-02-13 16:42 UTC, tijmenb commented on test/integration/indexer/indexing_test.rb
> +  def test_parts_of_taxonomy
Not sure about this integration test. Apps will never not send `part_of_taxonomy` directly via a POST.

Would it be better to skip this test and add something extra to the links lookup test?

2017-02-13 16:44 UTC, tijmenb requested changes

2017-02-13 16:44 UTC, tijmenb commented on test/integration/indexer/links_lookup_test.rb
> +      "part_of_taxonomy" => ["TAXON-1"],
It would be nice to add a full test of the behaviour here. So given a taxon with parents a & b, the  `part_of_taxonomy` of taxon c will be a, b & c.

2017-02-13 16:47 UTC, MatMoore commented on config/schema/field_definitions.json
> +    "description": "Any taxon tagged to the document and any of their ancestor taxons",
Yes,

So if you have the taxonomy

- Schools
   - Key stage 1
      - Maths
   - Key stage 2
     - Maths

And you tag a document to key stage 1 maths and key stage 2 maths, then:

The field is set to [ks1 maths, ks2 maths, ks1, ks2, schools]

And the document is returned in any of these searches:
 - ks1 maths
 - ks2 maths
 - ks1
 - ks2
 - schools

2017-02-13 17:00 UTC, tijmenb commented on config/schema/field_definitions.json
> +    "description": "Any taxon tagged to the document and any of their ancestor taxons",
Right of course. I confused myself, I think I was thinking of the way you retrieve the pages.

2017-02-14 09:13 UTC, MatMoore commented on config/schema/field_definitions.json
> +    "description": "Any taxon tagged to the document and any of their ancestor taxons",
Yeah it's a bit counterintuitive

2017-02-17 11:50 UTC, MatMoore commented
Have added a more complete test and rebased this onto master.

2017-02-17 14:37 UTC, tijmenb approved these changes

2017-02-17 14:37 UTC, merged