ADR records for multiple queuing systems and bunny-mock
alphagov/search-api pull request #837
Opened 2017-07-24 16:22 UTC by dwhenry

2017-07-26 09:21 UTC, brenetic requested changes

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +In order to simplify the search infrasture we are moving to using the publishing API
`infrastructure`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +projects, as current each publishing app has to implement a write interface into rummager.
`currently`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +* reduce the load on the publishing API - rummager current needs to retrieve tagging data
`currently`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +event has occurred, with the key specifying teh publishing app and the publishing event
`the`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +the message off the rabbitMQ stream, doing a small about of manipulation and then creating
`amount`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +processing inplace, or writting the message to a Sidekiq worker and then have it perform
`writing`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +the require processing.
`required`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +While it is possible to have implement all the above feature using just the rabbit MQ system
~~have~~

`features`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +diagram for the data flow through the system as well as a documented way to determin the status
`determine`

2017-07-26 09:21 UTC, brenetic commented on doc/arch/adr-001-use-of-both-rabbitmq-and-sidekiq-queues.md
> +new developers are clear when gems/libraries are assocaited with which queuing system.
~~when~~  => `which`

`associated`

2017-07-26 16:11 UTC, MatMoore reviewed
Got half way through reviewing before being distracted, so some of mine probably duplicate Brendan's. Other than a few typos, it looks good to me.

2017-07-27 15:36 UTC, dwhenry commented
@MatMoore @brenetic I have now completed the above updates.

I have removed the second ADR (it was just a placeholder) and will look to add that in a separate PR

2017-07-27 16:18 UTC, brenetic approved these changes

2017-07-27 16:18 UTC, merged