Doc supertypes
alphagov/search-api pull request #846
Opened 2017-08-02 11:02 UTC by suzannehamilton

Probably easiest to review commit-by-commit:

- Some refactoring commits to make it easier to add other types of boosting to sitemap priorities
- Apply more boosts to page priorities in the sitemap

  Internal search results are upweighted or downweighted based on several
properties of a document, such as whether it is guidance or whether it
is marked as historic (i.e. it is a publication by a previous
government).

  This commit applies the same boosts to *external* search by using them
as a multiplier in the sitemap priorities. This should improve the
relative rankings of GOV.UK pages in external search results, helping
users to find the information that they're more likely to be searching
for.

https://trello.com/c/wTcs0JaG/194-add-format-weightings-to-sitemap

2017-08-02 13:10 UTC, dwhenry requested changes
Looks really good, but you have left a couple of reference to `format_boost_calculator` when doing the refactor.

2017-08-03 09:17 UTC, suzannehamilton commented
Good spot! Now fixed. 👍

2017-08-03 10:15 UTC, dwhenry approved these changes
And just the one more. Happy for you to ignore and update later. :)

2017-08-03 10:15 UTC, dwhenry commented on lib/search/query_components/booster.rb
> +      format_boosts + [time_boost]
Might be worth renaming this variable as well :(

2017-08-07 08:43 UTC, suzannehamilton commented on lib/search/query_components/booster.rb
> +      format_boosts + [time_boost]
Done. 👍

2017-08-07 08:45 UTC, merged